use Employees;
SELECT ENAME, JOB, HIREDATE FROM emp;
SELECT ENAME, JOB, HIREDATE FROM emp WHERE DEPTNO = '10';
-- manager
SELECT ENAME, JOB, HIREDATE FROM emp WHERE JOB = 'MANAGER' AND SAL > 2800;-- 2 manager
SELECT ENAME, JOB, HIREDATE FROM emp WHERE JOB = 'MANAGER' AND DEPTNO != 30;-- 2 manager
-- employees beetwen 1200 and 1400
SELECT * FROM emp WHERE SAL > 1200 AND SAL < 1400;-- 3 employees
-- employees departement
SELECT * FROM emp WHERE DEPTNO >= 10 AND DEPTNO <= 30 ORDER BY ENAME;
-- employees salaire
SELECT * FROM emp WHERE DEPTNO = 30 ORDER BY SAL;
SELECT * FROM emp ORDER BY JOB, SAL DESC;
-- employees job
SELECT * FROM emp WHERE JOB = "ANALYST";
SELECT * FROM emp WHERE JOB = "CLERK";
SELECT * FROM emp WHERE JOB = "MANAGER";
SELECT * FROM emp WHERE JOB = "PRESIDENT";
SELECT * FROM emp WHERE JOB = "SALESMAN";
-- ALLEN
SELECT dept.DNAME FROM emp INNER JOIN dept ON emp.DEPTNO = dept.DEPTNO WHERE emp.ENAME = "ALLEN";




