name: Label sponsors
on:
  pull_request:
    branches: [master]
    types: [opened]
    
jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: autmerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
